/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Maria Savelyeva (https://sketchfab.com/erinsavel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walkman-1711a6c6ca1e472e8437eea3051994fb
Title: Walkman
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("/walkman.glb");
  return (
    <group {...props} scale={10} dispose={null}>
      <group
        position={[-0.004, 0.005, -0.001]}
        rotation={[-1.056, 0.202, 0.396]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[4.411, 1.597, -1.669]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel02_Wheel_0.geometry}
              material={materials.Wheel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel02_Wheel_Holes_0.geometry}
              material={materials.Wheel_Holes}
            />
          </group>
          <group
            position={[4.411, 1.403, -1.669]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel03_Wheel_0.geometry}
              material={materials.Wheel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel03_Wheel_Holes_0.geometry}
              material={materials.Wheel_Holes}
            />
          </group>
          <group
            position={[0.695, 1.638, 6.001]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            {/**Upload Area*/}
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Screen_0.geometry}
              material={new THREE.MeshBasicMaterial()}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Screen_Light_0.geometry}
              material={materials.Screen_Light}
            />
          </group>
          <group
            position={[-4.101, 0.969, -0.984]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base_Side_Base2_0.geometry}
              material={materials.Base2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base_Side_Base_0.geometry}
              material={materials.Base}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base_Side_Base3_0.geometry}
              material={materials.Base3}
            />
          </group>
          <group
            position={[0.123, 1.703, 1.026]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Decals_Holes_Holes_0.geometry}
              material={materials.Holes}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Decals_Holes_Holes_Switch_0.geometry}
              material={materials.Holes_Switch}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Decals_Holes_Holes_Casette_0.geometry}
              material={materials.Holes_Casette}
            />
          </group>
          <group
            position={[-0.233, 0.969, -5.739]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Input_Base3_0.geometry}
              material={materials.Base3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Input_Metal_0.geometry}
              material={materials.Metal}
            />
          </group>
          <group
            position={[2.927, 0.969, -6.199]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plug01_Metal_0.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plug01_Holes_0.geometry}
              material={materials.Holes}
            />
          </group>
          <group
            position={[-4.101, 2.146, -0.853]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Buttons_Buttons_Dark_0.geometry}
              material={materials.Buttons_Dark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Buttons_Buttons_0.geometry}
              material={materials.Buttons}
            />
          </group>
          <group
            position={[-0.303, 0.969, 2.168]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base_Yellow_Base_Yellow_0.geometry}
              material={materials.Base_Yellow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base_Yellow_Base_YellowDark_0.geometry}
              material={materials.Base_YellowDark}
            />
          </group>
          <group
            position={[5.296, 1.578, -0.985]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Decals_Sticker_Blue_0.geometry}
              material={materials.Sticker_Blue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Decals_Sticker_Paper_0.geometry}
              material={materials.Sticker_Paper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Decals_Base_YellowLight_0.geometry}
              material={materials.Base_YellowLight}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Decals_Glow_0.geometry}
              material={materials.Glow}
            />
          </group>
          <group
            position={[7.317, 1.589, -0.952]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Yellow_Base_YellowDark_0.geometry}
              material={materials.Base_YellowDark}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Casette_Yellow_Base_Yellow_0.geometry}
              material={materials.Base_Yellow}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Casette_Box_Casette_0.geometry}
            material={materials.Casette}
            position={[4.326, 1.463, -0.952]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plug02_Plug2_0.geometry}
            material={materials.Plug2}
            position={[4.245, 0.969, -6.199]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_Antenna_Base_0.geometry}
            material={materials.Base}
            position={[-6.628, 0.969, 0.252]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Switch_Switch_0.geometry}
            material={materials.Switch}
            position={[4.744, 1.913, 4.021]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_Base_0.geometry}
            material={materials.Base}
            position={[1.934, 0.969, 1.037]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Antenna_Metal_0.geometry}
            material={materials.Metal}
            position={[-6.827, 0.969, -5.202]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_CasetteHole_Base3_0.geometry}
            material={materials.Base3}
            position={[2.421, 1.202, -0.952]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_CasetteHole_Metal_Metal_0.geometry}
            material={materials.Metal}
            position={[-0.469, 1.207, -0.812]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel01_Wheel_Holes_0.geometry}
            material={materials.Wheel_Holes}
            position={[4.434, 1.583, -1.601]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Decals_Decals_0.geometry}
            material={materials.Decals}
            position={[0.559, 1.132, 3.403]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Screws_Metal_0.geometry}
            material={materials.Metal}
            position={[0.417, 0.969, 2.61]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Buttons_Dark_Buttons_Dark_0.geometry}
            material={materials.Buttons_Dark}
            position={[5.887, 0.969, 9.658]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_Window_0.geometry}
            material={materials.Window}
            position={[3.588, 1.631, -1.458]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box024_Bronze_0.geometry}
            material={materials.Bronze}
            position={[3.085, 1.267, -0.334]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plug03_Plug1_0.geometry}
            material={materials.Plug1}
            position={[0.559, 1.132, 3.403]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/walkman.glb");
